{% set name = "azure-purview-catalog" %}
{% set version = "1.0.0b4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/azure-purview-catalog-{{ version }}.zip
  sha256: ba65dcb4fc0ac22d858c63a892ce75e9122340dbb9eeaa571a12ca07f5a119da

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - msrest >=0.6.21
    - azure-core >=1.23.0,<2.0.0

test:
  imports:
    - azure.purview.catalog
    - azure.purview.catalog.aio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure Azure Purview Catalog Client Library for Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - redur
